/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// test_dev_1_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_READ_DATA                                       0x7d, 0xd1, 0x80, 0x67, 0xbd, 0x28, 0x4b, 0x4b, 0xbc, 0x1b, 0x39, 0x74, 0xd6, 0xf3, 0x40, 0x29
#define __UUID_READ_DATA_ALL_INPUT_DATA                        0x0a, 0x4b, 0x4c, 0x59, 0x3a, 0x4d, 0x48, 0x8f, 0x9c, 0xba, 0x9a, 0x39, 0x8b, 0x34, 0xdc, 0x0e
#define __UUID_READ_DATA_ALL_STD_OUTPUT_DATA                   0xb2, 0xf5, 0xee, 0x31, 0x70, 0x1b, 0x4c, 0x66, 0x90, 0xea, 0x42, 0x7b, 0x4b, 0xb8, 0x5f, 0x64
#define __UUID_READ_DATA_ALL_SETTINGS_DATA                     0xa5, 0xcf, 0x2d, 0x6c, 0x59, 0x3a, 0x43, 0xd3, 0xa5, 0x59, 0x5c, 0xed, 0xf8, 0x8d, 0xa7, 0x5f
#define __UUID_READ_DATA_ALL_SP_OUTPUT_DATA                    0x72, 0xb4, 0x09, 0x13, 0xf7, 0x4f, 0x47, 0xb8, 0xa3, 0x4a, 0x2a, 0x08, 0x74, 0x16, 0x62, 0x7e
#define __UUID_WRITE_DATA                                      0xad, 0x63, 0xd9, 0xeb, 0xf8, 0xb6, 0x48, 0x7c, 0x93, 0x38, 0xda, 0x7b, 0x06, 0x35, 0x57, 0x30
#define __UUID_WRITE_DATA_ALL_OUTPUT_CONFIG                    0xe9, 0xe9, 0xf5, 0xae, 0xef, 0x0b, 0x4a, 0x70, 0xb1, 0x40, 0x9d, 0xee, 0xf8, 0xbc, 0xc2, 0x9c

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                                 0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                                    0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME                        0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE                  0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE                         0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE                   0x0018

// ***** Primary Service 'Device Information'
#define HDLS_DEVICE_INFORMATION                                0x0028
// ----- Characteristic 'Manufacturer Name String'
#define HDLC_DEVICE_INFORMATION_MANUFACTURER_NAME_STRING       0x0029
#define HDLC_DEVICE_INFORMATION_MANUFACTURER_NAME_STRING_VALUE 0x002A
// ----- Characteristic 'Hardware Revision String'
#define HDLC_DEVICE_INFORMATION_HARDWARE_REVISION_STRING       0x002B
#define HDLC_DEVICE_INFORMATION_HARDWARE_REVISION_STRING_VALUE 0x002C
// ----- Characteristic 'Software Revision String'
#define HDLC_DEVICE_INFORMATION_SOFTWARE_REVISION_STRING       0x002D
#define HDLC_DEVICE_INFORMATION_SOFTWARE_REVISION_STRING_VALUE 0x002E

// ***** Primary Service 'read_data'
#define HDLS_READ_DATA                                         0x0040
// ----- Characteristic 'all_input_data'
#define HDLC_READ_DATA_ALL_INPUT_DATA                          0x0041
#define HDLC_READ_DATA_ALL_INPUT_DATA_VALUE                    0x0042
// ----- Characteristic 'all_std_output_data'
#define HDLC_READ_DATA_ALL_STD_OUTPUT_DATA                     0x0043
#define HDLC_READ_DATA_ALL_STD_OUTPUT_DATA_VALUE               0x0044
// ----- Characteristic 'all_settings_data'
#define HDLC_READ_DATA_ALL_SETTINGS_DATA                       0x0045
#define HDLC_READ_DATA_ALL_SETTINGS_DATA_VALUE                 0x0046
// ----- Characteristic 'all_sp_output_data'
#define HDLC_READ_DATA_ALL_SP_OUTPUT_DATA                      0x0047
#define HDLC_READ_DATA_ALL_SP_OUTPUT_DATA_VALUE                0x0048

// ***** Primary Service 'write_data'
#define HDLS_WRITE_DATA                                        0x0050
// ----- Characteristic 'all_output_config'
#define HDLC_WRITE_DATA_ALL_OUTPUT_CONFIG                      0x0051
#define HDLC_WRITE_DATA_ALL_OUTPUT_CONFIG_VALUE                0x0052

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table test_dev_1_gatt_db_ext_attr_tbl[];
extern const uint16_t test_dev_1_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
