/*
 *
 *  Copyright (c) 2020, Spudnik LLc <https://www.spudnik.com/>
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are not permitted in any form.
 *
 *  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 *  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION, DEATH, or SERIOUS INJURY or DAMAGE)
 *  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 *  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

package com.Diagnostic.Spudnik.Bluetooth;
@SuppressWarnings("unused")
public enum BroadcastActionConstants {

    ACTION_GATT_CONNECTED("com.Diagnostic.Spudnik.le.ACTION_GATT_CONNECTED"),
    ACTION_GATT_DISCONNECTED("com.Diagnostic.Spudnik.le.ACTION_GATT_DISCONNECTED"),
    ACTION_GATT_SERVICES_DISCOVERED( "com.Diagnostic.Spudnik.le.ACTION_GATT_SERVICES_DISCOVERED"),
    ACTION_GATT_SERVICES_DISCOVERED_FAILURE( "com.Diagnostic.Spudnik.le.ACTION_GATT_SERVICES_DISCOVERED_FAILURE"),
    ACTION_CHARACTERISTIC_READ( "com.Diagnostic.Spudnik.le.ACTION_CHARACTERISTIC_READ"),
    ACTION_CHARACTERISTIC_READ_FAILURE( "com.Diagnostic.Spudnik.le.ACTION_CHARACTERISTIC_READ_FAILURE"),
    ACTION_CHARACTERISTIC_WRITE( "com.Diagnostic.Spudnik.le.ACTION_CHARACTERISTIC_WRITE"),
    ACTION_CHARACTERISTIC__WRITE_FAILURE( "com.Diagnostic.Spudnik.le.ACTION_CHARACTERISTIC_WRITE_FAILURE"),
    ACTION_AUTORECONNECT_COMPLETE("com.Diagnostic.Spudnik.le.ACTION_AUTORECONNECT_COMPLETE"),
    ACTION_AUTORECONNECT_FAILURE("com.Diagnostic.Spudnik.le.ACTION_AUTORECONNECT_FAILURE");


    public final String string;
    BroadcastActionConstants(String s) {
        this.string = s;
    }
    public String getString() {
        return string;
    }
}
